# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: SUP3R-US3R
description: > # this means to ignore newlines until "baseurl:"
  Desenvolvido para meus projetos
baseurl: ""
url: "https://sup3r-us3r.github.io"
permalink: /:year/:month/:day/:title
repository: Sup3r-Us3r/sup3r-us3r.github.io
paginate: 5

# Sup3r-Us3r specific configurations
github_profile: "https://github.com/Sup3r-Us3r"
user: "Magno Tutor"
user_email: "pc.gam3rs.tuto@gmail.com"
contact_url: "https://goo.gl/forms/0KrExNpoHGOZHKVY2"
google_tracking_id: ""
google_site_verification: ""
disqus_shortname: "sup3r_us3r"

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  style: compressed
future: true
